### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
I am entering the programming world!

### CODE REVIEW

**Comment by ghost** [comment]
I am entering the programming world!

**Comment by ghost** [comment]
I am entering the programming world!

**Comment by ghost** [comment]
I am entering the programming world!

**Comment by ojaswa1942** [comment]
Why did you close the PR?

**Comment by ghost** [comment]
> Why did you close the PR?

Sir,I have yet to understand these things properly.
Infact I am not even aware what happened and how,so I think now I opened it and will do any thing further only after having some concrete knowledge!

**Pull request closed without merging**
